[package]
name = "micro-backend-framework"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
route-recognizer = "0.3.1"
serde = "1.0.132"